apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./repo-structure/one-to-one/flux-example/cluster-XXXX/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-xxxx-gitrepo
